package com.dino.message.corefeature.presentation.util

import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.navigation.NavController
import com.dino.message.DinoOrderApplication
import kotlinx.coroutines.flow.collectLatest


/**
 * Composable function that handles UI events by observing the UI event flow and performing corresponding navigation actions.
 *
 * @param app The application instance of type [DinoOrderApplication].
 * @param navController The [NavController] used for navigation.
 */
@Composable
fun HandleUIEvent(
    app: DinoOrderApplication,
    navController: NavController
) {
    LaunchedEffect(key1 = true) {
        app.uIEventFlow.collectLatest { event ->
            when (event) {
                is UIEvent.NavigateWithPopBackStack -> {
                    // Use event.route instead of event.direction
                    navController.navigate(event.route) {
                        // popUpTo logic remains the same
                        when (event.level) {
                            is PopBackStackLevel.ALL -> {
                                popUpTo(navController.graph.startDestinationId) {
                                    inclusive = true
                                }
                            }
                            is PopBackStackLevel.Number -> {
                                for (index in 0 until event.level.number) {
                                    if (navController.previousBackStackEntry != null) {
                                        navController.popBackStack()
                                    } else {
                                        break
                                    }
                                }
                            }
                        }
                    }
                }
                is UIEvent.Navigate -> {
                    // Use event.route instead of event.direction
                    navController.navigate(event.route)
                }
                is UIEvent.NavigateUp -> {
                    navController.navigateUp()
                }
                is UIEvent.ShowCustomMessageDialog -> {
                    // Assuming CustomMessageDialogScreenDestination expects CustomMessageDialogData
                    // and CustomMessageDialogData is now @Parcelize and its contents @Serializable
                    // or handled by a custom NavTypeSerializer for Compose Destinations
                    // If CustomMessageDialogScreenDestination is generated by Compose Destinations
                    // and expects CustomMessageDialogData, this should work if CustomMessageDialogData
                    // is Parcelable or you've set up a NavTypeSerializer.
                    // navController.navigate(CustomMessageDialogScreenDestination(event.data))
                }
                is UIEvent.ShowImageDialog -> {
                    // Similar to ShowCustomMessageDialog
                    // navController.navigate(ImageDialogScreenDestination(event.data))
                }
            }
        }
    }
}
